### ISSUE TITLE
[BUG] <Проблемы с сервером в последней ревизии>

### ISSUE THREAD

**Issue by Black-Judge** [NL0bP/AAEmu#121]
## _I confirm that:_
- [x] I understand that if I do not agree to the following points by marking the checkboxes my issue will be ignored.
- [x] I have searched existing [issues](https://github.com/AAEmu/AAEmu/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.
- [x] I am currently on the latest commit of the branch when reporting this bug

**Code branch that is affected by this issue** 

`AAEmu-client_version-3.0_client(2017-03-15)+`

**Bug description**

В последней ревизии сервера проявилась проблема которая заключается в циклическом спаме сообщений в терминале во время работы сервера. Также заметно выросла нагрузка на процессор.

Сообщения в терминале:

08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8617, objId 64073 FuncGroupId 24250 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8617, objId 64069 FuncGroupId 24250 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8617, objId 64053 FuncGroupId 24250 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8617, objId 64057 FuncGroupId 24250 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8616, objId 64032 FuncGroupId 24249 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8678, objId 64094 FuncGroupId 24255 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8395, objId 64023 FuncGroupId 23506 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8678, objId 64097 FuncGroupId 24255 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8678, objId 64096 FuncGroupId 24255 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8736, objId 64100 FuncGroupId 24256 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8618, objId 64085 FuncGroupId 24236 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8395, objId 64024 FuncGroupId 23506 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8705, objId 64099 FuncGroupId 24436 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8617, objId 64075 FuncGroupId 24250 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8673, objId 64091 FuncGroupId 24251 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8616, objId 64050 FuncGroupId 24249 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8617, objId 64059 FuncGroupId 24250 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8616, objId 64048 FuncGroupId 24249 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8678, objId 64093 FuncGroupId 24255 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8395, objId 64016 FuncGroupId 23506 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8616, objId 64045 FuncGroupId 24249 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8395, objId 64020 FuncGroupId 23506 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8395, objId 64018 FuncGroupId 23506 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8616, objId 64041 FuncGroupId 24249 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8617, objId 64065 FuncGroupId 24250 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: Doodad TemplateId 8617, objId 64071 FuncGroupId 24250 despawn [1] reschedule next time... 
08:34:04 [DEBUG] DoodadSpawner - DoSpawn: delay 00:00:00

**Steps to reproduce**

Скомпилировать последнюю сборку сервера, запустить сервер, наблюдать за сообщениями в терминале.

**Expected behavior**

**Screenshots**

https://youtu.be/za233DdCzoE

**Any additional context for this bug**

**Comment by NL0bP** [comment]
Неправильная работа расписания для Doodads & Npc.
Исправлено в PR 9b649983e58f82e3a40c86f0431ac70f27c247b3
