### ISSUE TITLE
[BUG] <Проблема с созданием гильдии>

### ISSUE THREAD

**Issue by Black-Judge** [NL0bP/AAEmu#125]
## _I confirm that:_
- [x] I understand that if I do not agree to the following points by marking the checkboxes my issue will be ignored.
- [x] I have searched existing [issues](https://github.com/AAEmu/AAEmu/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.
- [x] I am currently on the latest commit of the branch when reporting this bug

**Code branch that is affected by this issue** 

`AAEmu-client_version-3.0_client(2017-03-15)+`

**Bug description**

Проявилась проблема с созданием гильдии. Собравши отряд из пяти персонажей и подойдя к НПЦ, который регистрирует гильдии, нужно начать взаимодействие в результате которого создается гильдия, но на данный момент ничего не происходит.
В терминале появляется такая ошибка:

11:56:29 [ERROR] GameProtocolHandler - Unknown packet 0x1b(5) from 92.ххх.169.227:
09 00 53 69 6c 65 6e 74 69 75 6d 6c 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  

**Steps to reproduce**

Зайти персонажами в игру, объединиться в группу, подойти к НПЦ регистратору гильдии, лидером группы попытаться создать гильдию.

ИД НПЦ регистратора гильдии
16233 например

**Expected behavior**

**Screenshots**

![2024-06-07_12-04-36](https://github.com/NL0bP/AAEmu/assets/127834204/75b3a4c6-255f-4c97-8a2e-f735f146c049)
![2024-06-07_11-57-31](https://github.com/NL0bP/AAEmu/assets/127834204/22eb85e3-5896-42e6-8e85-a9d0d71a10a7)

**Any additional context for this bug**

**Comment by NL0bP** [comment]
Теперь гильдию можно создать.
