### ISSUE TITLE
[OTHER] <3.0 Данные клиента>

### ISSUE THREAD

**Issue by xy17012** [NL0bP/AAEmu#27]
**Шеф, я не знаю, есть ли проблема с моим клиентом или что происходит, то есть мой корабль не может ходить в море, где у вас есть соответствующий клиент 3.0 или данные?**

**Comment by Black-Judge** [comment]
Такое лучше спрашивать в чате в Дискорде, тут только правильно оформленные баг-репорты нужно размещать. Ответ на твой вопрос по ссылке https://github.com/NL0bP/AAEmu/issues/20
