### ISSUE TITLE
[BUG] <Баг с питомцем Золотая Мантикора>

### ISSUE THREAD

**Issue by Black-Judge** [NL0bP/AAEmu#45]
## _I confirm that:_
- [x] I understand that if I do not agree to the following points by marking the checkboxes my issue will be ignored.
- [x] I have searched existing [issues](https://github.com/AAEmu/AAEmu/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.
- [x] I am currently on the latest commit of the branch when reporting this bug

**Code branch that is affected by this issue** 

`AAEmu-client_version-3.0_client(2017-03-15)+`

**Bug description**

Возникла проблема с питомцем Золотая Мантикора ИД 8001750, после призыва данного питомца отсутствует панель взаимодействия с ним, присутствует возможность сесть верхом G, но слезть уже не получится.
**Steps to reproduce**

Войти в игру, призвать питомца Золотая Мантикора, попытаться сесть верхом, попытаться слезть с питомца.

**Expected behavior**

**Screenshots**

https://youtu.be/_o2xhnsDAzs

**Any additional context for this bug**

**Comment by NL0bP** [comment]
Исправлено, смотри [BUG] <Баг с питомцем Штормовой дракон> #53
