### ISSUE TITLE
[BUG] <Ограничение по сбору ресурсов до 53 уровня>

### ISSUE THREAD

**Issue by And70** [NL0bP/AAEmu#59]
Code branch that is affected by this issue

AAEmu-client_version-3.0_client(2017-03-15)+

Bug description

При использовании умения "Сбор урожая" персонажем 1 уровня появляется сообщение "Слишком низкий уровень" и ничего не происходит, невозможно собирать любые ресурсы до 53 уровня.
Ограничение связано с SCLevelRestrictionConfigPacket

**Comment by Black-Judge** [comment]
протестировал, ограничение установлено до 52 уровня, после достижения этого уровня персонажем сбор активируется.

**Comment by NL0bP** [comment]
Как проверить:
Создай перса, дай ему уровень например 30, посади любое растение и попробуй собрать.
/item add self 15659 семена картофеля

**Comment by NL0bP** [comment]
Использование клиента AAClassic 3.0.4.2 исправляет эту ошибку.
Можно собирать урожай с 1 уровня.

**Comment by Black-Judge** [comment]
в wiki нужно добавить информацию об особенностях разных клиентов
