### ISSUE TITLE
[BUG] <Проблема с рыбалкой>

### ISSUE THREAD

**Issue by Black-Judge** [NL0bP/AAEmu#85]
## _I confirm that:_
- [x] I understand that if I do not agree to the following points by marking the checkboxes my issue will be ignored.
- [x] I have searched existing [issues](https://github.com/AAEmu/AAEmu/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.
- [x] I am currently on the latest commit of the branch when reporting this bug

**Code branch that is affected by this issue** 

`AAEmu-client_version-3.0_client(2017-03-15)+`

**Bug description**

Проявилась проблема с рыбалкой, при попытке ловить рыбу с помощью удочки на червя происходит только анимация процесса, персонаж визуально ловит рыбу, начисляется очки опыта в Рыбной ловле и идет расход очков работы, но рыбы в инвентаре персонажа не появляется.

**Steps to reproduce**

Зайти в игру персонажем, создать удочку  ИД 27959 или ИД 30588, создать некоторое количество дождевых червей ИД 27142, экипировать удочку и начать процесс ловли рыбы.

**Expected behavior**

**Screenshots**

https://youtu.be/QRpw3noqHVQ

**Any additional context for this bug**

**Comment by NL0bP** [comment]
Для версии 3+ не хватает в таблицах лута данных, не знаю что делать.

**Comment by NL0bP** [comment]
Z посмотрел, и увидел, что лутпаки указаны в таблице zone_groups и это клиентская таблица, по аналогии с 1.2 можно сдублировать данные для рыбалки в 3.0.3 в таблице loot (серверная таблица).
Готово. Сдублировал данные для 3.0.3.
Нет данных:
для id=11989 zone=78 o_dew_plains
для id=11960 zone=57 o_ruins_of_gold
Что это за территории и что за лут там может быть?
