### ISSUE TITLE
[BUG] <Проблема [WARN] GameObject - CanAttack zone faction is null 232467 - 238108>

### ISSUE THREAD

**Issue by Black-Judge** [NL0bP/AAEmu#92]
## _I confirm that:_
- [x] I understand that if I do not agree to the following points by marking the checkboxes my issue will be ignored.
- [x] I have searched existing [issues](https://github.com/AAEmu/AAEmu/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.
- [x] I am currently on the latest commit of the branch when reporting this bug

**Code branch that is affected by this issue** 

`AAEmu-client_version-3.0_client(2017-03-15)+`

**Bug description**

Проявилась проблема в локациях Долина талых снегов и Долина цветущих прудов. Если персонаж находится в этих локациях в логе постоянно появляются сообщения и файл WARN очень быстро наполняется однотипными данными.

/move 6294.3 9490.4 458.4 - Долина цветущих прудов
/move 28111.0 9956.7 866.0 - Долина талых снегов

сообщения в логе:

10:53:13 [WARN] GameObject - CanAttack zone faction is null 232467 - 238108
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238109 - 238107
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238111 - 238112
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238112 - 232467
10:53:13 [WARN] GameObject - CanAttack zone faction is null 232467 - 238108
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238109 - 238107
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238111 - 238112
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238112 - 232467
10:53:13 [WARN] GameObject - CanAttack zone faction is null 232467 - 238108
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238109 - 238107
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238111 - 238112
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238112 - 232467
10:53:13 [WARN] GameObject - CanAttack zone faction is null 232467 - 238108
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238109 - 238107
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238111 - 238112
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238112 - 232467
10:53:13 [WARN] GameObject - CanAttack zone faction is null 232467 - 238108
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238109 - 238107
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238111 - 238112
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238112 - 232467
10:53:13 [WARN] GameObject - CanAttack zone faction is null 232467 - 238108
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238109 - 238107
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238111 - 238112
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238112 - 232467
10:53:13 [WARN] GameObject - CanAttack zone faction is null 232467 - 238108
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238109 - 238107
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238111 - 238112
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238112 - 232467
10:53:13 [WARN] GameObject - CanAttack zone faction is null 232467 - 238108
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238109 - 238107
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238111 - 238112
10:53:13 [WARN] GameObject - CanAttack zone faction is null 238112 - 232467
10:53:14 [WARN] GameObject - CanAttack zone faction is null 232467 - 238108
10:53:14 [WARN] GameObject - CanAttack zone faction is null 238109 - 238107
**Steps to reproduce**

Зайти в игру персонажем, переместиться в данные локации, наблюдать за сообщениями в терминале сервера.
/move 6294.3 9490.4 458.4 - Долина цветущих прудов
/move 28111.0 9956.7 866.0 - Долина талых снегов

**Expected behavior**

**Screenshots**

![2024-05-14_10-55-56](https://github.com/NL0bP/AAEmu/assets/127834204/ef0e4991-7abe-430b-a945-cad32020a17f)
![2024-05-14_10-54-37](https://github.com/NL0bP/AAEmu/assets/127834204/95a158d8-2cd9-4ec2-97b1-ba4f7e07fe76)

**Any additional context for this bug**

**Comment by NL0bP** [comment]
Ищется Фракция = 5, а такой в таблице нет.
Тут просто спам сообщениями, а на самом деле берется нейтральная фракция = 2.
Вариант:
1. закомментировать это сообщение или
3. сделать его не Warn, а типа Trace, чтобы не было его видно.
