### ISSUE TITLE
[BUG] <Баг с группированием предметов в инвентаре>

### ISSUE THREAD

**Issue by Black-Judge** [NL0bP/AAEmu#94]
## _I confirm that:_
- [x] I understand that if I do not agree to the following points by marking the checkboxes my issue will be ignored.
- [x] I have searched existing [issues](https://github.com/AAEmu/AAEmu/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.
- [x] I am currently on the latest commit of the branch when reporting this bug

**Code branch that is affected by this issue** 

`AAEmu-client_version-3.0_client(2017-03-15)+`

**Bug description**

Проявилась ошибка с группированием предметов в инвентаре персонаже, предметы с обычным уровнем группируются как и положено, предметы с уровнем выше обычного складываются отдельно в ячейки в инвентаре персонажа, что в итоге приводит к переполнению инвентаря. Ручное группирование предметов функционирует.

**Steps to reproduce**

Зайти в игру персонажем, создать например семена растений с обычным уровнем (картофель) и уровнем выше обычного (тыква), собрать урожай, наблюдать за инвентарем где обычные предметы будут группироваться, а с уровнем выше обычного будут складываться в отдельные ячейки, сделать ручное группирование предметов в инвентаре.

ИД картофеля /item add self 15659 1000 0

ИД тыквы /item add self 15666 1000 2

**Expected behavior**

**Screenshots**

https://youtu.be/K3YRYZEEuSg

**Any additional context for this bug**

**Comment by NL0bP** [comment]
Как решение: не проверять уровень грейда предметов при добавлении в инвентарь.
https://i.gyazo.com/f590d0732fc54cd8457bb88be6b8f99e.gif
